name: "Vulnerability Scan Integration with ASC"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODEOWNERS'

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: docker build . -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/test:${{ github.sha }}
        name: docker build
      - uses: Azure/container-scan@v0
        name: scan images for vulnerabilities
        id: container_scan
        continue-on-error: true
        with:
          image-name: ${{ secrets.REGISTRY_NAME }}.azurecr.io/test:${{ github.sha }}
          severity-threshold: MEDIUM
          run-quality-checks: true
      - uses: Azure/docker-login@v1
        name: acr login
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/test:${{ github.sha }}
        name: docker push
      - uses: azure/publish-security-assessments@v0
        name: Post logs to appinsights
        with:
          artifact-type: containerImage
          scan-provider: trivy
          scan-results-path: ${{ steps.container_scan.outputs.scan-report-path }}
          connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
          subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
